// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

interface ISpendingManager {
    // ─── Structs ──────────────────────────────────────────────────────────────

    struct BatchTransfer {
        address  recipient;
        uint256  amount;
        uint256  nonce;
        bytes[]  signatures;
    }

    /// @notice Defines the required signature weight for a range of transfer amounts.
    ///         Tiers are stored sorted by maxAmount ascending.
    ///         threshold must be > 0. Amounts above the highest tier's maxAmount are forbidden.
    struct AmountTier {
        uint256 maxAmount;  // upper bound (inclusive); amount <= maxAmount → use this tier
        uint256 threshold;  // required sum of valid signer weights; must be > 0
    }

    // ─── Events ───────────────────────────────────────────────────────────────

    event Paused(address indexed account);
    event Unpaused(address indexed account);
    event ManagerAdded(address indexed manager, uint256 weight);
    event ManagerRemoved(address indexed manager);
    event ManagerLimitsUpdated(
        address indexed manager,
        uint256 daily,
        uint256 weekly,
        uint256 monthly,
        uint256 total
    );
    event ManagerWeightUpdated(address indexed manager, uint256 newWeight);
    event TiersUpdated();
    event GlobalLimitsUpdated(
        uint256 daily,
        uint256 weekly,
        uint256 monthly,
        uint256 total
    );
    event ManagerSpentUpdated(
        address indexed manager,
        uint256 daily,
        uint256 weekly,
        uint256 monthly,
        uint256 total
    );
    event GlobalSpentUpdated(
        uint256 daily,
        uint256 weekly,
        uint256 monthly,
        uint256 total
    );
    event TransferExecuted(
        address indexed submitter,
        address indexed recipient,
        uint256 amount,
        uint256 nonce
    );
    event TransferRejected(
        address indexed submitter,
        address indexed recipient,
        uint256 amount,
        uint256 nonce,
        string reason
    );

    // ─── Owner functions ──────────────────────────────────────────────────────

    function pause() external;
    function unpause() external;

    function addManager(
        address manager,
        uint256 weight,
        uint256 daily,
        uint256 weekly,
        uint256 monthly,
        uint256 total
    ) external;

    function removeManager(address manager) external;

    function updateManagerLimits(
        address manager,
        uint256 daily,
        uint256 weekly,
        uint256 monthly,
        uint256 total
    ) external;

    function updateManagerWeight(address manager, uint256 newWeight) external;

    /// @notice Replace all amount tiers. Tiers must be sorted by maxAmount ascending.
    ///         Each tier's threshold must be > 0 and <= totalActiveWeight.
    ///         Amounts above the highest tier's maxAmount are forbidden.
    function setTiers(AmountTier[] calldata newTiers) external;

    function setGlobalLimits(
        uint256 daily,
        uint256 weekly,
        uint256 monthly,
        uint256 total
    ) external;

    function setManagerSpent(
        address manager,
        uint256 daily,
        uint256 weekly,
        uint256 monthly,
        uint256 total
    ) external;

    function setGlobalSpent(
        uint256 daily,
        uint256 weekly,
        uint256 monthly,
        uint256 total
    ) external;

    // ─── Manager functions ────────────────────────────────────────────────────

    /// @notice Submit a single pre-signed transfer. Only callable by an active manager.
    /// @param recipient  Token destination address
    /// @param amount     Token amount (in token's smallest unit)
    /// @param nonce      Unique nonce generated by the backend; prevents replay
    /// @param signatures Array of 65-byte ECDSA signatures. Each signature must be produced
    ///                   with the EIP-191 personal-sign prefix via TronLink's signMessageV2():
    ///                   sign( keccak256(abi.encodePacked(address(this), recipient, amount, nonce)) )
    function execute(
        address recipient,
        uint256 amount,
        uint256 nonce,
        bytes[] calldata signatures
    ) external;

    /// @notice Submit up to MAX_BATCH_SIZE transfers in a single transaction.
    ///         MAX_BATCH_SIZE is set in the constructor and immutable.
    ///         Each transfer is evaluated independently: insufficient weight,
    ///         a used nonce, or a forbidden amount emits TransferRejected and
    ///         skips that element; it does NOT revert the entire batch.
    function executeBatch(BatchTransfer[] calldata transfers) external;

    // ─── View functions ───────────────────────────────────────────────────────

    function owner() external view returns (address);
    function token() external view returns (address);
    function getTiers() external view returns (AmountTier[] memory);
    function paused() external view returns (bool);
    function totalActiveWeight() external view returns (uint256);
    function isManager(address manager) external view returns (bool);
    function isNonceUsed(uint256 nonce) external view returns (bool);
}
